# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Consensus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'

end
